### ISSUE TITLE
Feature request: use Android 11+ media style for controls notification

### ISSUE THREAD

**Issue by NorthFred** [ingageco/capacitor-music-controls-plugin-v3#11] opened 2023-05-08 07:06 UTC
Referring to the Cordova equivalent of this plugin: https://github.com/ghenry22/cordova-plugin-music-controls2

In this plugin, the notification has been updated to show different media style for the notification. This Capacitor plugin could also benefit from this, especially now since the controls notification does not show up anymore on API 33+ (see issue https://github.com/ingageco/capacitor-music-controls-plugin-v3/issues/7).

**Comment by ingageco** [comment] 2023-05-08 14:44
@NorthFred Very nice, i'll look into the differences and start working on it

**Comment by NorthFred** [comment] 2023-05-08 15:42
@ingageco Great 👍!

**Comment by NorthFred** [comment] 2023-06-13 07:36
@ingageco Any updates? I'm eager to have a working solution for API levels 33+...

**Comment by ingageco** [comment] 2023-06-13 10:53
I do t have any updates at the moment. I plan on making some app updates this week, and will update this to meet any needs we have for Android 13

**Comment by ingageco** [comment] 2023-06-14 12:46
Ok I'll find that reference. Must have missed something

**Comment by ingageco** [comment] 2023-06-14 12:52
@NorthFred Updated - re-pull the branch. i confirmed that it'll build on its own, so there shouldn't be any simple errors like this.

**Comment by ingageco** [comment] 2023-06-14 13:17
@NorthFred Awesome! could you screenshot just so i have a reference?

Does it still ask for permissions of any sort? 

Im going to try to do my own testing on this the remainder of the week, but it's a crazy personal week + we are on watch for our 2nd child. Send whatever you find, and i'll address it asap!

**Comment by ingageco** [comment] 2023-06-15 14:22
@NorthFred in my initial test, a few things: 

1. the notification permission is still asked the first time the controls are created
2. the play/pause button work as expected
3. dismissing the media controls correctly kills the audio in the app, and the audio stops playing, but notification does not dismiss

**Comment by NorthFred** [comment] 2023-06-15 14:26
@ingageco Did you test on Android 13? On Android 8-12, the controls are working, but I'm facing the problems with Android 13... I haven't seen the notification permission on any version.

**Comment by ingageco** [comment] 2023-06-15 14:35
Api level 33 is android 13

**Comment by NorthFred** [comment] 2023-06-15 14:48
Please make sure to also target API 33 when building the app (in `variables.gradle`). I get a different outcome when I still have API 32 marked as target.

These are my settings:

```
    minSdkVersion = 22
    compileSdkVersion = 33
    targetSdkVersion = 33
```

**Comment by ingageco** [comment] 2023-06-15 18:07
@NorthFred Ahhhhh... now im on the same page as you.

**Comment by ingageco** [comment] 2023-06-15 19:15
@NorthFred I've copied over just about everything that I can from the cordova version of the plugin. With the exception of the cordova-specific code, i think they are close to identical. However, the play/pause button still doesn't work in 13. 

One thing i have discovered about 13 - swiping the media controls DOES make it go away, but it is not an actual dismissal of the notification. It hides it. Swipe down again after swiping it away, and i'll see it still exists there.

**Comment by NorthFred** [comment] 2023-06-16 10:28
@ingageco There are no errors printed to the console for the Play/Pause button, only following message is registered:

```
I/CapacitorMusicControls: controlsNotification fired music-controls-media-button-pause
V/Capacitor/CapacitorMusicControls: Notifying listeners for event controlsNotification
```

**Comment by NorthFred** [comment] 2023-06-16 10:33
As for the hiding of the media controls: when swiping down again, the media controls are still shown in the status page and on 2nd try, they can no longer be dismissed.

**Comment by ingageco** [comment] 2023-06-16 16:06
@NorthFred Read this: https://github.com/ionic-team/capacitor/issues/6234

Appears to be a capacitor bug with notifying the listeners. "Solution" is to use the legacy android JS bridge, by placing: 

`
android: {
useLegacyBridge: true
}
`

in your capacitor.config.ts config file

**Comment by ingageco** [comment] 2023-06-16 17:14
@NorthFred doing this causes issues for me. I believe the capacitor bug may be related to running the notification as a foreground service. before this branch, we didn't run it as a foreground service, but i integrated those changes from the other repo because of reports that the audio was stopping after 5min for that plugin. Not knowing if that was the case with our plugin / our apps, i went ahead and integrated it. Turns out, my apps aren't currently affected by that - at least with the current version of this plugin / Android 12. 

So i guess the next thing I can do is create a new branch and ONLY integrate the android 13 style changes to see if that will work, without changing it to run as a foreground service. If that doesn't work, i dont have any other solutions, and we both may just have to see if the cordova version will run in our projects for the near future.

**Comment by ingageco** [comment] 2023-06-16 18:08
@NorthFred No dice on android 13 style only. Looks like we're going to have to see what we can do about the notifyListeners not sending the button events back to the app via the JS bridge.

**Comment by ingageco** [comment] 2023-06-16 21:17
I've done everything i can to try to get this to work. At this point, there's no more progress to make unless that JS bridge bug is fixed. Even using the legacy Bridge has not worked for me, but i'll keep trying that angle to see if i can get it to work until capacitor issues the fix.

**Comment by ingageco** [comment] 2023-06-20 12:33
@NorthFred Good news! It really bothered me to have this roadblock - i have multiple media apps that we have for clients. I just can't sit around and wait for the Cap team to fix this. So i dug into the docs, and found that there is another way to communicate with the application via Java - triggerJSEvent

I just tested it, and .... the application actually is notified, unlike the recommended method by Capacitor! I'll post an update soon - it does require that you change how you listen for updates.

**Comment by NorthFred** [comment] 2023-06-20 12:51
@ingageco Wow! That is great news and I am happy to hear that there might be a solution after all. I have been testing with the capacitor.config.ts flag that you mentioned, but was hitting a wall with all the attempts. I can't wait to try out your solution, and I am feeling hopeful again that this will work by the time of the API level 33 target deadline this August!

**Comment by ingageco** [comment] 2023-06-20 13:25
@NorthFred Update your version of the android-13-style branch and differentiate between android and ios using this code: 

`
// the handler for android

        document.addEventListener('controlsNotification', (event) => {

          console.log('event received:');
          console.log(event);
          const action = { message : event.message, position: 0 };
          self.handleControlsEvent(action);
        });		

// the handler for ios (unchanged)

    
        CapacitorMusicControls.addListener('controlsNotification', (action) => {

          self.handleControlsEvent(action);
        });		
        
`

**Comment by NorthFred** [comment] 2023-06-20 14:57
@ingageco First test is successful! This looks promising indeed! I will do some further in-depth testing during the next 2 days and will report back if there are any findings. Thanks a lot altready, is there a way I could buy you a coffee? :)

**Comment by NorthFred** [comment] 2023-06-20 16:06
@ingageco Thanks for the kind words :) I'm actually a software tester by profession, but I do some light coding as a hobby :)

**Comment by NorthFred** [comment] 2023-06-20 16:11
@ingageco On Android API 34 I am running into a lot of messages like the one below. The app is hardly usable on the emulator because of it. Now, Android API 33 is reporting the same but it doesn't show as many of them as on API 34. It seems these are starting to come when the plugin gets registered during start-up of the application. I didn't have this with the main branch of the app:

```
I/Choreographer: Skipped 68 frames!  The application may be doing too much work on its main thread.
```

**Comment by ingageco** [comment] 2023-06-20 16:15
It happens when you call adding an event listener or immediately on open?

**Comment by ingageco** [comment] 2023-06-20 18:51
@NorthFred I'm not seeing any of that in my logs on 33 - zero. Booting up a 34 emulator to check. 

When i researched this, most of the consensus was this was either harmless or would go away with Invalidate Caches/Rebuild

**Comment by ingageco** [comment] 2023-06-20 22:38
@NorthFred Android API 34 is in beta and not going to reach general availability for a long time. So I suggest we keep focus to 33 for now, which is making it's way to devices now. 

It's possible that the issues on 34 are Capacitor related and have nothing to do with our code. We are prob a little ahead of the curve there.

**Comment by NorthFred** [comment] 2023-06-21 07:09
@ingageco We can leave it out of scope for the time being, it also requires some further investigation from my side.

**Comment by NorthFred** [comment] 2023-06-21 07:13
One observation with this plugin is that the controls are not destroyed when closing the application. This happens in 2 instances:

A.
- Open your application
- Play some music for some time (media controls are created)
- Close the application
==> The media controls persist.

B.
- Open the application
- Play some music and stop the music (media controls are created, no active streams)
- Put the application to the background
- Wait for e.g. 15 minutes
==> The system will close the application, but the media controls are still visible.

**Comment by ingageco** [comment] 2023-06-21 13:57
@NorthFred lets move your last comments to a new issue and close this one

**Closed** 2023-06-21 17:20 UTC
